spring.application.name=ipass-test
spring.datasource.url=jdbc:postgresql://localhost:5433/tasks
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.web.locale=pt_BR
spring.web.locale-resolver=accept-header
